version: '3.8'

services:
  zerepy-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./.env:/app/.env
    environment:
      - MOCK_LLM=true  # Force mock mode for LLM responses
      - PYTHONUNBUFFERED=1  # Ensure Python output is unbuffered for better logging
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    restart: unless-stopped
