version: '3.8'

services:
  zerepy-api:
    build:
      context: .
      dockerfile: Dockerfile.custom
    ports:
      - "8000:8000"
    environment:
      - MOCK_LLM=true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
